#!/usr/bin/env python3
"""Regenerate wiki/Rule-Catalog.md from the rule YAML files.

    pip install pyyaml
    python scripts/gen-catalog.py
"""
import collections
import glob
import os
import re

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "wiki", "Rule-Catalog.md")

PACK_TITLES = {
    "pyhton": "Python", "js": "JavaScript / TypeScript", "php": "PHP", "go": "Go",
    "java": "Java", "ruby": "Ruby", "rust": "Rust", "c": "C / C++",
    "csharp": "C# / .NET", "infra": "Infrastructure (compose / Dockerfile / nginx)",
}
FILE_KIND = {
    "backend": "backend (original)", "frontend": "frontend / views", "extra": "extra (original)",
    "taint": "taint / dataflow", "ad-logic": "A&D logic",
}


def short(msg: str, n: int = 140) -> str:
    msg = " ".join(str(msg).split())
    msg = msg.replace("|", "\\|")
    return msg if len(msg) <= n else msg[: n - 1].rstrip() + "…"


def kind_of(fname: str) -> str:
    base = re.sub(r"\(\d+\)$", "", os.path.splitext(os.path.basename(fname))[0])
    return FILE_KIND.get(base, base)


def main() -> None:
    packs = collections.OrderedDict()
    for pack in PACK_TITLES:
        files = sorted(glob.glob(os.path.join(REPO, pack, "*.yaml")))
        if files:
            packs[pack] = files

    lines = [
        "# Rule Catalog",
        "",
        "> Generated by `scripts/gen-catalog.py` - do not edit by hand.",
        "",
        "Severity: **E** = ERROR, **W** = WARNING, **I** = INFO. "
        "Impact is the `metadata.ad-impact` tag (only set on the new packs).",
        "",
    ]
    total = 0
    summary = []
    body = []
    for pack, files in packs.items():
        body += [f"## {PACK_TITLES[pack]}", ""]
        pack_total = 0
        for f in files:
            rules = (yaml.safe_load(open(f, encoding="utf-8")) or {}).get("rules", [])
            rel = os.path.relpath(f, REPO).replace("\\", "/")
            body += [f"### `{rel}` - {kind_of(f)} ({len(rules)} rules)", "",
                     "| Rule ID | Sev | CWE | Impact | Description |",
                     "|---|---|---|---|---|"]
            for r in rules:
                md = r.get("metadata") or {}
                cwe = md.get("cwe", "")
                if isinstance(cwe, list):
                    cwe = ", ".join(cwe)
                body.append(
                    f"| `{r['id']}` | {str(r.get('severity', ''))[:1]} | {cwe} | "
                    f"{md.get('ad-impact', '')} | {short(r.get('message', ''))} |")
            body.append("")
            pack_total += len(rules)
        summary.append(f"| {PACK_TITLES[pack]} | `{pack}/` | {len(files)} | {pack_total} |")
        total += pack_total

    lines += ["| Pack | Folder | Files | Rules |", "|---|---|---|---|"] + summary
    lines += [f"| **Total** | | | **{total}** |", ""] + body
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {OUT} ({total} rules)")


if __name__ == "__main__":
    main()
